# docker-compose.yml

version: '3.8'
services:
  postgres:
    # 사용할 docker 이미지 정의 (postgres 이미지의 13버전의 linux기반 경량 postgres 이미지)
    image: postgres:13-alpine
    restart: always
    # 초기화 중에 컨테이너에 전달되는 환경 변수를 지정 (컨테이너가 사용할 사용자이름, 비밀번호 등)
    # environment:
    #   - POSTGRES_USER=vohis
    #   - POSTGRES_PASSWORD=voh1sis

    env_file:
      - ./.env
    # 호스트 파일 시스템에 데이터를 유지하는 데 사용
    volumes:
      - postgres:/var/lib/postgresql/data
    # 호스트포트:컨테이너포트 형식 호스트 시스템의 포트를 컨테이너 5432 포트에 매핑
    ports: 
      - '5432:5432'

volumes:
  postgres:
